const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.Button,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.SetVar
	];
};
self.C3_JsPropNameTable = [
	{PlanoDeFundoEmBlocos: 0},
	{Sólido: 0},
	{Sprite: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{CentrarEm: 0},
	{Player: 0},
	{animação: 0},
	{Teclado: 0},
	{Senóide: 0},
	{Joia: 0},
	{Âncora: 0},
	{Pontuação: 0},
	{Texto: 0},
	{ação: 0},
	{inimigo1: 0},
	{marcador: 0},
	{Sprite2: 0},
	{espinhos: 0},
	{Sprite3: 0},
	{Áudio: 0},
	{Sprite4: 0},
	{Mouse: 0},
	{Botão: 0},
	{Sprite6: 0},
	{Sprite5: 0},
	{Pontos: 0}
];

self.InstanceType = {
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	animação: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Joia: class extends self.ISpriteInstance {},
	Pontuação: class extends self.ITextInstance {},
	Texto: class extends self.ITextInstance {},
	inimigo1: class extends self.ISpriteInstance {},
	marcador: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	espinhos: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Botão: class extends self.IButtonInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {}
}